server:
  port: 8080
spring:
  application:
    name: control-center

router:
  countryCode: 86
  localPortForUdpLinkLayer: 4000
  remoteAddressForUdpLinkLayer: 192.168.137.9:4001
  macAddress: 00:0e:8E:52:A8:19
  stationId: 1