server:
  port: 8080
spring:
  application:
    name: control-center
  # jpa 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SmartTraffic?serverTimezone=UTC
  #pc机地址
#    url: jdbc:mysql://111.200.0.19:3306/SmartTraffic?serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #开启mapper扫描，添加分页插件
  type-aliases-package: com.xue.entity  #定义实体类位置，写xml可以轻松点

# mybatis sql打印
logging:
  level:
    zhejianglab.mapper: debug


router:
  countryCode: 86
  localPortForUdpLinkLayer: 4000
  remoteAddressForUdpLinkLayer: 192.168.3.2:4001
  macAddress: 00:26:B6:F5:3F:0B
  stationId: 66