server:
  port: 8080
spring:
  application:
    name: control-center

router:
  countryCode: 86
  localPortForUdpLinkLayer: 4000
  remoteAddressForUdpLinkLayer: 192.168.3.2:4001
  macAddress: 00:26:B6:F5:3F:0B
  stationId: 66